// data.js
export const initialData = [
  {
    key: "1",
    imageAndStatus: "Hình ảnh và trạng thái 1",
    order: 1,
    readingLine: "Tuyến đọc 1",
    contractNumber: "Số hợp đồng 1",
    clockSen: "Sen đồng hồ 1",
    customerName: "Tên khách hàng 1",
    address: "Địa chỉ 1",
    moneyCollected: "Tiền thu 1",
    oldIndex: "Chỉ số cũ 1",
    newIndex: "Chỉ số mới 1",
    consumption: "Tiêu thụ 1",
    readingDate: "Ngày đọc 1",
  },
  {
    key: "2",
    imageAndStatus: "Hình ảnh và trạng thái 2",
    order: 2,
    readingLine: "Tuyến đọc 2",
    contractNumber: "Số hợp đồng 2",
    clockSen: "Sen đồng hồ 2",
    customerName: "Tên khách hàng 2",
    address: "Địa chỉ 2",
    moneyCollected: "Tiền thu 2",
    oldIndex: "Chỉ số cũ 2",
    newIndex: "Chỉ số mới 2",
    consumption: "Tiêu thụ 2",
    readingDate: "Ngày đọc 2",
  },
  {
    key: "3",
    imageAndStatus: "Hình ảnh và trạng thái 2",
    order: 3,
    readingLine: "Tuyến đọc 2",
    contractNumber: "Số hợp đồng 2",
    clockSen: "Sen đồng hồ 2",
    customerName: "Tên khách hàng 2",
    address: "Địa chỉ 2",
    moneyCollected: "Tiền thu 2",
    oldIndex: "Chỉ số cũ 2",
    newIndex: "Chỉ số mới 2",
    consumption: "Tiêu thụ 2",
    readingDate: "Ngày đọc 2",
  },
  {
    key: "4",
    imageAndStatus: "Hình ảnh và trạng thái 2",
    order: 4,
    readingLine: "Tuyến đọc 2",
    contractNumber: "Số hợp đồng 2",
    clockSen: "Sen đồng hồ 2",
    customerName: "Tên khách hàng 2",
    address: "Địa chỉ 2",
    moneyCollected: "Tiền thu 2",
    oldIndex: "Chỉ số cũ 2",
    newIndex: "Chỉ số mới 2",
    consumption: "Tiêu thụ 2",
    readingDate: "Ngày đọc 2",
  },
  {
    key: "5",
    imageAndStatus: "Hình ảnh và trạng thái 2",
    order: 5,
    readingLine: "Tuyến đọc 2",
    contractNumber: "Số hợp đồng 2",
    clockSen: "Sen đồng hồ 2",
    customerName: "Tên khách hàng 2",
    address: "Địa chỉ 2",
    moneyCollected: "Tiền thu 2",
    oldIndex: "Chỉ số cũ 2",
    newIndex: "Chỉ số mới 2",
    consumption: "Tiêu thụ 2",
    readingDate: "Ngày đọc 2",
  },
];
