const constants = {
  // menu 1
  RECEIPT_DOC: "RECEIPT_DOC",
  ACCEPTANCE_DOC: "ACCEPTANCE_DOC",
  DESIGN_DOC: "DESIGN_DOC",
  // menu 2
  REGISTRATION_FORM: "REGISTRATION_FORM",
  ESTIMATES: "ESTIMATES",
  CONTRACT_MANAGER: "CONTRACT_MANAGER",
  COVERAGE_RATE: "COVERAGE_RATE",
  NUMBER_MANAGEMENT: "NUMBER_MANAGEMENT",
  // menu 3
  READINGS_INDEX: "READINGS_INDEX",
  ENTER_INDEX: "ENTER_INDEX",
  BILL_ORDER: "BILL_ORDER",
  PRINT_BILL_ORDER: "PRINT_BILL_ORDER",
  EXPORT_PRINT_BILL_ORDER: "EXPORT_PRINT_BILL_ORDER",
};

export default constants;
